name: CD Pipeline - prod

on:
  push:
    branches:
      - prod

jobs:

  # ===============================
  # JOB 1 - SCAN SECURITE
  # ===============================
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Scan vulnerabilites avec Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: tatydl/intranet-newdeal:1.0.0
          format: table
          exit-code: '1'
          ignore-unfixed: true
          severity: CRITICAL

  # ===============================
  # JOB 2 - DEPLOIEMENT
  # ===============================
  deploy:
    needs: scan
    runs-on: self-hosted
    steps:
      - name: Pull latest image
        shell: powershell
        run: |
          docker pull tatydl/intranet-newdeal:1.0.0

      - name: Stop existing container
        shell: powershell
        run: |
          docker stop intranet-app; $LASTEXITCODE = 0

      - name: Remove old container
        shell: powershell
        run: |
          docker rm intranet-app; $LASTEXITCODE = 0

      - name: Run new container
        shell: powershell
        run: |
          docker run -d `
            -p 80:80 `
            --name intranet-app `
            tatydl/intranet-newdeal:1.0.0

  # ===============================
  # JOB 3 - NOTIFICATION EMAIL
  # ===============================
  notify:
    needs: [scan, deploy]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Send email notification
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.gmail.com
          server_port: 587
          secure: false
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "CD Pipeline - intranet-newdeal - ${{ github.ref_name }}"
          to: moussawade@groupeisi.com
          from: ${{ secrets.MAIL_USERNAME }}
          body: |
            Le pipeline CD sur la branche prod s est termine.
            Repository : ${{ github.repository }}
            Commit : ${{ github.sha }}
