name: CI Pipeline - dev

on:
  push:
    branches:
      - dev

env:
  IMAGE_NAME: intranet-newdeal
  IMAGE_TAG: 1.0.0
  DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:

  # ===============================
  # JOB 1 - BUILD IMAGE DOCKER
  # ===============================
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          docker build -t ${DOCKER_USER}/intranet-newdeal:1.0.0 .

      - name: Verify image
        run: |
          docker image ls | grep intranet-newdeal

  # ===============================
  # JOB 2 - SCAN SECURITE
  # ===============================
  scan:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build Docker image for scan
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          docker build -t ${DOCKER_USER}/intranet-newdeal:1.0.0 .

      - name: Scan vulnerabilites avec Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/intranet-newdeal:1.0.0
          format: table
          exit-code: '0'
          ignore-unfixed: true
          severity: CRITICAL,HIGH

      - name: Scan secrets avec Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          scanners: secret
          format: table
          exit-code: '0'

  # ===============================
  # JOB 3 - PUSH IMAGE DOCKER HUB
  # ===============================
  push:
    needs: scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push Docker image
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          docker build -t ${DOCKER_USER}/intranet-newdeal:1.0.0 .
          docker push ${DOCKER_USER}/intranet-newdeal:1.0.0
